spring:
  datasource:
    url: jdbc:postgresql://db.blanchaert.com:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver # optional
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/postgres

logging:
  level:
    org.flywaydb.core: DEBUG
